version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
