version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - "@types/eslint"
          - "@typescript-eslint/*"
          - "eslint"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
      swc:
        patterns:
          - "@swc/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
